<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="bai2"
    targetNamespace="http://tempuri.org/bai2.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/bai2.xsd"
    xmlns:mstns="http://tempuri.org/bai2.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:complexType name="HD">
		<xs:sequence> 
			<xs:element name="LoaiHang" maxOccurs="10">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="MaLoai"></xs:element>
						<xs:element name="Hang" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="TenHang" type="xs:string"></xs:element>
									<xs:element name="SoLuong" type="xs:int"></xs:element>
									<xs:element name="DonViTinh" >
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="goi"/>
												<xs:enumeration value="hop"/>
												<xs:enumeration value="chiec"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="DonGia" >
										<xs:simpleType>
											<xs:restriction base="xs:double">
												<xs:minInclusive value="0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="MaHang">
									<xs:simpleType>
										<xs:restriction base="xs:ID">
											<xs:maxLength value="6"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="TenLoai" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="MaHD" type="xs:string"/>
	</xs:complexType>
</xs:schema>
